AKSW/jekyll-rdf

.gitignore, lib/jekyll/drops/rdf_resource.rb, lib/jekyll/drops/rdf_resource_class.rb, lib/jekyll/filters/rdf_property.rb, lib/jekyll/filters/rdf_property_list.rb, lib/jekyll/rdf_main_generator.rb, lib/jekyll/rdf_template_mapper.rb
Referenced Issues: #3 , #11 , #9 , #2 , #8 
To #8 
Now, the browser path of each rendered uri might look weird:
the file for \<http//:www.dkonrad-zuse-akademie-hoyerswerda.de#id\>
resides in /rdfsites/http/www_dkonrad-zuse-akademie-hoyerswerda_dde#id/index.html
which might be impractical to use unless we provide some sort of parser to easily find the rendition
of each resource
=> The changes referenced on the Projectboard

Rakefile, lib/jekyll/drops/rdf_resource.rb, lib/jekyll/rdf_main_generator.rb, lib/jekyll/rdf_template_mapper.rb, test/source/Gemfile, test/source/_config.yml, test/test_helper.rb, test/test_jekyll-rdf.rb, test/test_rdf_page_data.rb
Fix tests to run locally and on travis.
supersedes #28
=> Fix tests to run without problems

lib/jekyll-rdf.rb, lib/jekyll/drops/rdf_resource.rb, lib/jekyll/rdf_main_generator.rb, lib/jekyll/rdf_page_data.rb, test/source/_config.yml, test/source/rdf-data/simpsons.ttl, test/test_helper.rb, test/test_jekyll-rdf.rb, test/test_rdf_main_generator.rb, test/test_rdf_page_data.rb
=> Serving Resources under Configured URL

lib/jekyll/rdf_main_generator.rb, test/test_rdf_main_generator.rb
=>  Show Warning if jekyll-rdf is not configured

lib/jekyll/drops/rdf_resource.rb, test/test_rdf_page_data.rb
=> blanknode recognition during path building

lib/jekyll/rdf_main_generator.rb, lib/jekyll/rdf_page_data.rb, test/test_rdf_main_generator.rb, test/test_rdf_page_data.rb
=> default templates are not mandantory anymore

README.md, lib/jekyll/filters/rdf_property.rb, test/test_jekyll-rdf.rb
fixes #23 
also done some refactoring to improve the performance of `rdf_property`
the inverse is implemented through another filter instead of a flag, in order to keep the same api aviable
=> Inverse property helper

test/source/Gemfile
could potentially lead to Issue #50, if bundler is used
=> fix path attribute of gemspec

README.md
adresses Issue #55
it does not change anything in the code, but is more precise in [Defining Prefixes for RDF](https://github.com/white-gecko/jekyll-rdf#defining-prefixes-for-rdf)
=> corrected the paragraph about Prefix files

lib/jekyll-rdf.rb, lib/jekyll/drops/rdf_resource.rb, test/source/rdf-data/simpsons.ttl
=> replace umlauts in uri file names

README.md
=> corrected README.md

jekyll-rdf.gemspec, lib/jekyll/filters/rdf_collection.rb, lib/jekyll/filters/rdf_container.rb
=> Filter for container collection

jekyll-rdf.gemspec
This at least fixes the gemspec for travis builds
=> Maybe fix gemspec

lib/jekyll/filters/rdf_container.rb
=> container sequences are now ordered

lib/jekyll/drops/rdf_resource.rb, lib/jekyll/drops/rdf_term.rb, lib/jekyll/rdf_generator_helper.rb, test/source/_config.yml, test/source/_layouts/main.html, test/source/rdf-data/simpsons.ttl
Fix #86, #85 
Please test if these changes fixed the given test examples
=> repair render_path and page_url

lib/jekyll/drops/rdf_term.rb, test/test_rdf_template_mapper.rb
=> equality operators are now supported

lib/jekyll/drops/rdf_resource.rb, lib/jekyll/drops/rdf_statement.rb, lib/jekyll/drops/rdf_term.rb, test/test_rdf_inspect.rb
=> implemented inspect method

README.md
=> 95 improve examples

lib/jekyll/filters/rdf_collection.rb
=> missing include in rdf_collection

test/test_helper.rb, test/test_rdf_filters.rb, test/test_rdf_main_generator.rb, test/test_rdf_page_data.rb
=> cleaned up tests

lib/jekyll/helper/rdf_generator_helper.rb, test/source/_config.yml, test/source/_layouts/askcovered.html, test/source/_layouts/covered.html, test/source/rdf-data/simpsons.ttl, test/test_jekyll-rdf.rb
=> fix covered bug

lib/jekyll/helper/rdf_page_helper.rb, lib/jekyll/rdf_page_data.rb, test/ResourceHelper.rb, test/test_rdf_page_data.rb
=> squash this with 252a1be4e5040b8864f354dc2f9cec550e8fddce

lib/jekyll/filters/rdf_get.rb, lib/jekyll/filters/rdf_page_to_resource.rb, test/source/_config.yml, test/source/_layouts/test_rdf_get.html, test/source/rdf-data/simpsons.ttl, test/test_helper.rb, test/test_rdf_filters.rb, test/test_rdf_main_generator.rb
=> rdf_get now rereturns input resources

lib/jekyll/filters/rdf_get.rb, lib/jekyll/filters/rdf_page_to_resource.rb, lib/jekyll/filters/rdf_sparql_query.rb, test/source/_config.yml, test/source/_layouts/show_rdf_get.html, test/source/_layouts/sites_covered.html, test/source/rdf-data/simpsons.ttl, test/test_rdf_filters.rb
Fix #173 
rdf_get wont process any blanknodes anymore
=> rdf_get now maps pages correctly

lib/jekyll/filters/rdf_get.rb, test/source/_layouts/covered.html, test/test_rdf_filters.rb, test/test_rdf_main_generator.rb
=> rdf_get now also returns uncovered pages

lib/jekyll/helper/rdf_general_helper.rb, lib/jekyll/hooks/rdf_page_pointer.rb, test/source/ex/prefixes/prefixes.html, test/source/rdf-data/prefixes.pref, test/test_jekyll-rdf.rb, test/test_rdf_filters.rb
=> Prefix front matters now work on non-RDF-Pages

lib/jekyll/rdf_main_generator.rb, test/test_helper.rb, test/test_rdf_filters.rb, test/test_rdf_inspect.rb, test/test_rdf_main_generator.rb, test/test_rdf_page_data.rb, test/test_rdf_template_mapper.rb
Fix #187.
Thanks to: https://gist.github.com/jpravetz/1424893
=> Interprete graph path relative to source path

lib/jekyll/filters/rdf_sparql_query.rb
=> sparql_query wont change static strings

lib/jekyll/helper/rdf_generator_helper.rb, lib/jekyll/helper/rdf_page_helper.rb, test/cases/LinkTag/Gemfile, test/cases/LinkTag/_config.yml, test/cases/LinkTag/_data/knowledge-base.ttl, test/cases/LinkTag/_layouts/default.html, test/cases/LinkTag/links.html, test/test_rdf_page_data.rb
=> Set relative_path on pages for link tag to work

lib/jekyll/helper/rdf_general_helper.rb, test/cases/emptyLinePrefixFile/Gemfile, test/cases/emptyLinePrefixFile/_config.yml, test/cases/emptyLinePrefixFile/_data/Prefixes.pref, test/cases/emptyLinePrefixFile/_data/knowledge-base.ttl, test/cases/emptyLinePrefixFile/_layouts/default.html, test/cases/emptyLinePrefixFile/_layouts/exampleInstance.html, test/cases/emptyLinePrefixFile/_layouts/person.html, test/test_cases.rb
=> empty line in prefixfile do not cause problems anymore

lib/jekyll/filters/rdf_container.rb, test/cases/shortcutContainers/Gemfile, test/cases/shortcutContainers/_config.yml, test/cases/shortcutContainers/_data/Prefixes.pref, test/cases/shortcutContainers/_data/knowledge-base.ttl, test/cases/shortcutContainers/_layouts/default.html, test/cases/shortcutContainers/_layouts/exampleInstance.html, test/cases/shortcutContainers/_layouts/person.html, test/cases/shortcutContainers/container.html, test/cases/shortcutContainers/test_shortcut_container.rb
This does the same as #116 just for Containers.
=> Add support for anonymous containers

lib/jekyll/drops/rdf_resource.rb, test/cases/drops/test_rdf_drops.rb
=> blank nodes don't have IRIs

lib/jekyll/rdf_main_generator.rb, test/cases/mainPrefixFile/Gemfile, test/cases/mainPrefixFile/_config.yml, test/cases/mainPrefixFile/_data/Prefixes.pref, test/cases/mainPrefixFile/_data/knowledge-base.ttl, test/cases/mainPrefixFile/mainPrefixTest.html, test/cases/mainPrefixFile/test_main_prefix_file.rb
=> removed rdf-data requirement from .pref file

lib/jekyll/filters/rdf_sparql_query.rb, lib/jekyll/helper/rdf_prefix_helper.rb, lib/jekyll/rdf_template_mapper.rb, test/cases/filter/test_rdf_filters.rb
=> messages and raises are JEKYLL_ENV dependent

lib/jekyll-rdf.rb, lib/jekyll/filters/rdf_debug_message.rb
=> rename rdf_message -> rdf_debug_message

lib/jekyll/hooks/rdf_page_pointer.rb
=> add hooks for posts and documents

lib/jekyll/filters/rdf_resolve_prefix.rb, lib/jekyll/helper/rdf_generator_helper.rb, lib/jekyll/rdf_main_generator.rb, test/cases/listExtraction/Gemfile, test/cases/listExtraction/_config.yml, test/cases/listExtraction/_data/Prefixes.pref, test/cases/listExtraction/_data/knowledge-base.ttl, test/cases/listExtraction/_data/restriction.txt, test/cases/listExtraction/_layouts/default.html, test/cases/listExtraction/_layouts/exampleInstance.html, test/cases/listExtraction/_layouts/person.html, test/cases/listExtraction/test_list_restriction.rb
Fix #216 
prefixes for such list are not jet implemented
=> enable rendering resources from a list

lib/jekyll/rdf_main_generator.rb, lib/jekyll/rdf_template_mapper.rb, test/cases/multipleWarnings/Gemfile, test/cases/multipleWarnings/_config.yml, test/cases/multipleWarnings/_data/Prefixes.pref, test/cases/multipleWarnings/_data/knowledge-base.ttl, test/cases/multipleWarnings/_layouts/default.html, test/cases/multipleWarnings/_layouts/layout1.html, test/cases/multipleWarnings/_layouts/layout10.html, test/cases/multipleWarnings/_layouts/layout11.html, test/cases/multipleWarnings/_layouts/layout12.html, test/cases/multipleWarnings/_layouts/layout2.html, test/cases/multipleWarnings/_layouts/layout3.html, test/cases/multipleWarnings/_layouts/layout4.html, test/cases/multipleWarnings/_layouts/layout5.html, test/cases/multipleWarnings/_layouts/layout6.html, test/cases/multipleWarnings/_layouts/layout7.html, test/cases/multipleWarnings/_layouts/layout8.html, test/cases/multipleWarnings/_layouts/layout9.html, test/cases/multipleWarnings/test_multiple_warnings.rb
=> Reduce warnings during template mapping

lib/jekyll/drops/rdf_resource.rb, test/cases/renderedAttribute/Gemfile, test/cases/renderedAttribute/_config.yml, test/cases/renderedAttribute/_data/Prefixes.pref, test/cases/renderedAttribute/_data/knowledge-base.ttl, test/cases/renderedAttribute/_layouts/default.html, test/cases/renderedAttribute/rendered.html, test/cases/renderedAttribute/test_rendered_attribute.rb
=> Add resource.rendered

CHANGELOG.md, README.md
=> Update changelog, add new features to README, and fix typos

lib/jekyll/rdf_main_generator.rb
=> Fix: Render all resources if restrictions are empty

lib/jekyll/drops/rdf_resource.rb, lib/jekyll/drops/rdf_term.rb, lib/jekyll/filters/rdf_get.rb, lib/jekyll/filters/rdf_property.rb, lib/jekyll/helper/rdf_general_helper.rb, lib/jekyll/helper/rdf_generator_helper.rb, test/RdfTestUtility.rb, test/cases/filter/test_rdf_filters.rb, test/cases/uniqueResources/Gemfile, test/cases/uniqueResources/_config.yml, test/cases/uniqueResources/_data/Prefixes.pref, test/cases/uniqueResources/_data/knowledge-base.ttl, test/cases/uniqueResources/_layouts/default.html, test/cases/uniqueResources/test_unique_resources.rb, test/cases/uniqueResources/uniqueResources.html
=> Create resources only once

README.md
=> Change page to page.rdf in README.

lib/jekyll/hooks/rdf_page_pointer.rb, test/cases/filter/test_rdf_filters.rb, test/cases/resetSite/Gemfile, test/cases/resetSite/_config.yml, test/cases/resetSite/_data/Prefixes.pref, test/cases/resetSite/_data/knowledge-base.ttl, test/cases/resetSite/_layouts/default-resource.html, test/cases/resetSite/_layouts/default.html, test/cases/resetSite/_layouts/exampleInstance.html, test/cases/resetSite/_layouts/person.html, test/cases/resetSite/reset-page.html, test/cases/resetSite/test_reset.rb
=> jekyll-rdf still works after Jekyll reset

lib/jekyll/drops/rdf_resource.rb, test/cases/noElongatedPageNames/Gemfile, test/cases/noElongatedPageNames/_config.yml, test/cases/noElongatedPageNames/_data/knowledge-base.ttl, test/cases/noElongatedPageNames/page.html, test/cases/noElongatedPageNames/test_url_elongation.rb
=> page_url wont constantly add .html after each refresh

test/cases/restrictions/Gemfile, test/cases/restrictions/_config.yml, test/cases/restrictions/_data/Prefixes.pref, test/cases/restrictions/_data/knowledge-base.ttl, test/cases/restrictions/_data/restriction-file.rf, test/cases/restrictions/_layouts/default.html, test/cases/restrictions/test_restriction.rb
=> Tests for the different restriction forms
